
FROM drecom/centos-base:7 AS rubybuild
RUN git clone git://github.com/rbenv/ruby-build.git /usr/local/plugins/ruby-build \
&&  /usr/local/plugins/ruby-build/install.sh
RUN yum -y install jemalloc-devel
RUN RUBY_CONFIGURE_OPTS=--with-jemalloc ruby-build 2.7.3 /usr/local/

#------------------------------------------------------------------------
#------------------------------------------------------------------------

FROM newrelic/infrastructure:latest-centos

ENV PATH /usr/local/bin:$PATH
RUN yum -y install \
        epel-release
RUN yum update -y; \
	curl -sL https://rpm.nodesource.com/setup_10.x | bash -; \
	yum -y install \
	jemalloc-devel \
	make \
	gcc-c++ \
	gcc \
	git \
	openssl-devel \
	zlib-devel \
	mysql-devel \
	redis \
	sqlite-devel \
	bzip2 \
	nodejs \
	ImageMagick \
	ImageMagick-devel

COPY --from=rubybuild /usr/local /usr/local

RUN gem update --system
