FROM 874166547043.dkr.ecr.us-east-2.amazonaws.com/cenit-upgrade-base:upgrade.io.latest

#RUN git clone --single-branch --branch upgrading https://github.com/cenit-io/cenit.git /var/www/cenit
RUN git clone --single-branch --branch upgrading https://testCenitUpgradeVelosimo:YnSdS3j4isHELtMhlZR0Yagdx5TwJ*12@github.com/testCenitUpgradeVelosimo/cenit.git /var/www/cenit

WORKDIR /var/www/cenit

RUN mkdir -p /var/www/shared/log
RUN mkdir -p /var/www/shared/pids
RUN mkdir -p /var/www/shared/sockets

ENV RAILS_ENV='production'
ENV RACK_ENV='production'
ENV UNICORN_CENIT_SERVER=true

RUN gem install bundler:1.17.3

RUN bundle update mimemagic

RUN bundle install --jobs 20 --retry 5 --without development test